server:
  port: 8080

spring:
  application:
    name: lucky-b-key
  
  datasource:
    url: jdbc:mysql://localhost:3306/lucky_b_key?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&connectExpiredPassword=true
    username: ${DB_USERNAME:luckybuser}
    password: ${DB_PASSWORD:hackathon123!}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: false
  
  # Spring Security 설정
  security:
    web:
      firewalls:
        strict-http-firewall:
          allow-url-encoded-slash: true
          allow-semicolon: true
          allow-backslash: true
          allow-url-encoded-double-slash: true
          allow-url-encoded-percent: true
          allow-url-encoded-period: true

# JWT 설정
jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-here-change-this-in-production-this-must-be-at-least-512-bits-long-for-hs512-algorithm-to-work-properly-and-securely}
  expiration: 86400000 # 24시간 (밀리초)

# OpenAI 설정
openai:
  api-key: ${OPENAI_API_KEY:your-openai-api-key-here}
  model: gpt-3.5-turbo
  max-tokens: 1000

# 로깅 설정
logging:
  level:
    com.luckyb: debug
    org.springframework.security: debug

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

# AWS S3 설정 (기본값은 빈 문자열로 설정하여 S3 기능 비활성화)
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:}
      secret-key: ${AWS_SECRET_KEY:}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    s3:
      bucket: ${AWS_S3_BUCKET:} 