server:
  port: 8080

spring:
  application:
    name: lucky-b-key
  
  datasource:
    url: jdbc:mariadb://localhost:3306/lucky_b_key?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    defer-datasource-initialization: false
  
  # Spring Security 설정
  security:
    web:
      firewalls:
        strict-http-firewall:
          allow-url-encoded-slash: true
          allow-semicolon: true
          allow-backslash: true
          allow-url-encoded-double-slash: true
          allow-url-encoded-percent: true
          allow-url-encoded-period: true

# JWT 설정
jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-here-change-this-in-production-this-must-be-at-least-512-bits-long-for-hs512-algorithm-to-work-properly-and-securely}
  expiration: 86400000 # 24시간 (밀리초)

# 로깅 설정
logging:
  level:
    com.luckyb: debug
    org.springframework.security: debug 