spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

# 테스트용 JWT 설정
jwt:
  secret: test-secret-key-for-jwt-token-generation-and-validation-this-must-be-at-least-512-bits-long-for-hs512-algorithm
  expiration: 86400000

# 로깅 레벨 낮춤
logging:
  level:
    com.luckyb: info
    org.springframework.security: warn 