server:
  port: 8080

spring:
  application:
    name: lucky-b-key
  
  datasource:
    url: jdbc:mariadb://localhost:3306/lucky_b_key?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    defer-datasource-initialization: false

# JWT 설정
jwt:
  secret: ${JWT_SECRET:lucky-b-key-secret-key-for-jwt-token-generation-and-validation-this-must-be-at-least-512-bits-long-for-hs512-algorithm-to-work-properly}
  expiration: 86400000 # 24시간 (밀리초)

# 로깅 설정
logging:
  level:
    com.luckyb: debug
    org.springframework.security: debug 