server:
  port: 8080

spring:
  application:
    name: lucky-b-key

  datasource:
    # H2 in-memory database for testing
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    # PostgreSQL for production
    # url: jdbc:postgresql://localhost:5432/lucky_b_key
    # username: ${DB_USERNAME:postgres}
    # password: ${DB_PASSWORD:password}
    # driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# JWT 설정
jwt:
  secret: ${JWT_SECRET:lucky-b-key-secret-key-for-jwt-token-generation-and-validation-this-must-be-at-least-512-bits-long-for-hs512-algorithm-to-work-properly}
  expiration: 86400000 # 24시간 (밀리초)

# 로깅 설정
logging:
  level:
    com.luckyb: DEBUG
    org.springframework.security: DEBUG 